export default [
  {
    id: 1,
    firstName: "Adam",
    lastName: "Anderson",
    role: "CEO",
    department: "Management",
    phoneNumber: "555-1212",
  },
  {
    id: 2,
    firstName: "Bill",
    lastName: "Sanders",
    role: "Manager",
    department: "Human Resources",
    phoneNumber: "555-3434",
  },
  {
    id: 3,
    firstName: "Charlie",
    lastName: "Tango",
    role: "Software Engineer",
    department: "Engineering",
    phoneNumber: "555-4545",
  },
  {
    id: 4,
    firstName: "Romeo",
    lastName: "Foxtrot",
    role: "Test Engineer",
    department: "Engineering",
    phoneNumber: "555-5656",
  },
  {
    id: 5,
    firstName: "Doug",
    lastName: "Peters",
    role: "Sales Associate",
    department: "Sales",
    phoneNumber: "555-6767",
  },
  {
    id: 6,
    firstName: "Donna",
    lastName: "Walters",
    role: "Accountant",
    department: "Accounting",
    phoneNumber: "555-7878",
  },
  {
    id: 7,
    firstName: "Kelly",
    lastName: "Martinez",
    role: "Sales Associate",
    department: "Sales",
    phoneNumber: "555-8989",
  },
  {
    id: 8,
    firstName: "Roddy",
    lastName: "Rich",
    role: "Sales Associate",
    department: "Sales",
    phoneNumber: "555-9090",
  },
  {
    id: 9,
    firstName: "Dwight",
    lastName: "Kruger",
    role: "Janitor",
    department: "Maintenance",
    phoneNumber: "555-0101",
  },
  {
    id: 10,
    firstName: "Jim",
    lastName: "Zax",
    role: "Accountant",
    department: "Accounting",
    phoneNumber: "555-1234",
  },
  {
    id: 11,
    firstName: "Anna",
    lastName: "Shortt",
    role: "Hardware Engineer",
    department: "Engineering",
    phoneNumber: "555-2345",
  },
  {
    id: 12,
    firstName: "Chris",
    lastName: "Richards",
    role: "Electrical Engineer",
    department: "Engineering",
    phoneNumber: "555-3456",
  },
  {
    id: 13,
    firstName: "Dante",
    lastName: "Jones",
    role: "Intern",
    department: "Engineering",
    phoneNumber: "555-4567",
  },
];